/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.hl7.fhir.avro.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ValueSetPointer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -600567361188901003L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ValueSetPointer\",\"namespace\":\"org.hl7.fhir.avro.models\",\"fields\":[{\"name\":\"valueSet\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ValueSetPointer> ENCODER =
      new BinaryMessageEncoder<ValueSetPointer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ValueSetPointer> DECODER =
      new BinaryMessageDecoder<ValueSetPointer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ValueSetPointer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ValueSetPointer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ValueSetPointer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ValueSetPointer>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ValueSetPointer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ValueSetPointer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ValueSetPointer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ValueSetPointer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence valueSet;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ValueSetPointer() {}

  /**
   * All-args constructor.
   * @param valueSet The new value for valueSet
   */
  public ValueSetPointer(java.lang.CharSequence valueSet) {
    this.valueSet = valueSet;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return valueSet;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: valueSet = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'valueSet' field.
   * @return The value of the 'valueSet' field.
   */
  public java.lang.CharSequence getValueSet() {
    return valueSet;
  }


  /**
   * Sets the value of the 'valueSet' field.
   * @param value the value to set.
   */
  public void setValueSet(java.lang.CharSequence value) {
    this.valueSet = value;
  }

  /**
   * Creates a new ValueSetPointer RecordBuilder.
   * @return A new ValueSetPointer RecordBuilder
   */
  public static org.hl7.fhir.avro.models.ValueSetPointer.Builder newBuilder() {
    return new org.hl7.fhir.avro.models.ValueSetPointer.Builder();
  }

  /**
   * Creates a new ValueSetPointer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ValueSetPointer RecordBuilder
   */
  public static org.hl7.fhir.avro.models.ValueSetPointer.Builder newBuilder(org.hl7.fhir.avro.models.ValueSetPointer.Builder other) {
    if (other == null) {
      return new org.hl7.fhir.avro.models.ValueSetPointer.Builder();
    } else {
      return new org.hl7.fhir.avro.models.ValueSetPointer.Builder(other);
    }
  }

  /**
   * Creates a new ValueSetPointer RecordBuilder by copying an existing ValueSetPointer instance.
   * @param other The existing instance to copy.
   * @return A new ValueSetPointer RecordBuilder
   */
  public static org.hl7.fhir.avro.models.ValueSetPointer.Builder newBuilder(org.hl7.fhir.avro.models.ValueSetPointer other) {
    if (other == null) {
      return new org.hl7.fhir.avro.models.ValueSetPointer.Builder();
    } else {
      return new org.hl7.fhir.avro.models.ValueSetPointer.Builder(other);
    }
  }

  /**
   * RecordBuilder for ValueSetPointer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ValueSetPointer>
    implements org.apache.avro.data.RecordBuilder<ValueSetPointer> {

    private java.lang.CharSequence valueSet;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.hl7.fhir.avro.models.ValueSetPointer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.valueSet)) {
        this.valueSet = data().deepCopy(fields()[0].schema(), other.valueSet);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ValueSetPointer instance
     * @param other The existing instance to copy.
     */
    private Builder(org.hl7.fhir.avro.models.ValueSetPointer other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.valueSet)) {
        this.valueSet = data().deepCopy(fields()[0].schema(), other.valueSet);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'valueSet' field.
      * @return The value.
      */
    public java.lang.CharSequence getValueSet() {
      return valueSet;
    }


    /**
      * Sets the value of the 'valueSet' field.
      * @param value The value of 'valueSet'.
      * @return This builder.
      */
    public org.hl7.fhir.avro.models.ValueSetPointer.Builder setValueSet(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.valueSet = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'valueSet' field has been set.
      * @return True if the 'valueSet' field has been set, false otherwise.
      */
    public boolean hasValueSet() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'valueSet' field.
      * @return This builder.
      */
    public org.hl7.fhir.avro.models.ValueSetPointer.Builder clearValueSet() {
      valueSet = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ValueSetPointer build() {
      try {
        ValueSetPointer record = new ValueSetPointer();
        record.valueSet = fieldSetFlags()[0] ? this.valueSet : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ValueSetPointer>
    WRITER$ = (org.apache.avro.io.DatumWriter<ValueSetPointer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ValueSetPointer>
    READER$ = (org.apache.avro.io.DatumReader<ValueSetPointer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.valueSet);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.valueSet = in.readString(this.valueSet instanceof Utf8 ? (Utf8)this.valueSet : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.valueSet = in.readString(this.valueSet instanceof Utf8 ? (Utf8)this.valueSet : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










