/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.carrera.fhir.avro.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Instant extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6386713983533016313L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Instant\",\"namespace\":\"io.carrera.fhir.avro.models\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"record\",\"name\":\"XsDateTime\",\"fields\":[{\"name\":\"millis\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"zoneId\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<Instant> ENCODER =
      new BinaryMessageEncoder<Instant>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Instant> DECODER =
      new BinaryMessageDecoder<Instant>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Instant> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Instant> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Instant> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Instant>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Instant to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Instant from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Instant instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Instant fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private io.carrera.fhir.avro.models.XsDateTime value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Instant() {}

  /**
   * All-args constructor.
   * @param value The new value for value
   */
  public Instant(io.carrera.fhir.avro.models.XsDateTime value) {
    this.value = value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (io.carrera.fhir.avro.models.XsDateTime)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public io.carrera.fhir.avro.models.XsDateTime getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(io.carrera.fhir.avro.models.XsDateTime value) {
    this.value = value;
  }

  /**
   * Creates a new Instant RecordBuilder.
   * @return A new Instant RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Instant.Builder newBuilder() {
    return new io.carrera.fhir.avro.models.Instant.Builder();
  }

  /**
   * Creates a new Instant RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Instant RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Instant.Builder newBuilder(io.carrera.fhir.avro.models.Instant.Builder other) {
    if (other == null) {
      return new io.carrera.fhir.avro.models.Instant.Builder();
    } else {
      return new io.carrera.fhir.avro.models.Instant.Builder(other);
    }
  }

  /**
   * Creates a new Instant RecordBuilder by copying an existing Instant instance.
   * @param other The existing instance to copy.
   * @return A new Instant RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Instant.Builder newBuilder(io.carrera.fhir.avro.models.Instant other) {
    if (other == null) {
      return new io.carrera.fhir.avro.models.Instant.Builder();
    } else {
      return new io.carrera.fhir.avro.models.Instant.Builder(other);
    }
  }

  /**
   * RecordBuilder for Instant instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Instant>
    implements org.apache.avro.data.RecordBuilder<Instant> {

    private io.carrera.fhir.avro.models.XsDateTime value;
    private io.carrera.fhir.avro.models.XsDateTime.Builder valueBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.carrera.fhir.avro.models.Instant.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasValueBuilder()) {
        this.valueBuilder = io.carrera.fhir.avro.models.XsDateTime.newBuilder(other.getValueBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Instant instance
     * @param other The existing instance to copy.
     */
    private Builder(io.carrera.fhir.avro.models.Instant other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
      this.valueBuilder = null;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public io.carrera.fhir.avro.models.XsDateTime getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Instant.Builder setValue(io.carrera.fhir.avro.models.XsDateTime value) {
      validate(fields()[0], value);
      this.valueBuilder = null;
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'value' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.carrera.fhir.avro.models.XsDateTime.Builder getValueBuilder() {
      if (valueBuilder == null) {
        if (hasValue()) {
          setValueBuilder(io.carrera.fhir.avro.models.XsDateTime.newBuilder(value));
        } else {
          setValueBuilder(io.carrera.fhir.avro.models.XsDateTime.newBuilder());
        }
      }
      return valueBuilder;
    }

    /**
     * Sets the Builder instance for the 'value' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public io.carrera.fhir.avro.models.Instant.Builder setValueBuilder(io.carrera.fhir.avro.models.XsDateTime.Builder value) {
      clearValue();
      valueBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'value' field has an active Builder instance
     * @return True if the 'value' field has an active Builder instance
     */
    public boolean hasValueBuilder() {
      return valueBuilder != null;
    }

    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Instant.Builder clearValue() {
      value = null;
      valueBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Instant build() {
      try {
        Instant record = new Instant();
        if (valueBuilder != null) {
          try {
            record.value = this.valueBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("value"));
            throw e;
          }
        } else {
          record.value = fieldSetFlags()[0] ? this.value : (io.carrera.fhir.avro.models.XsDateTime) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Instant>
    WRITER$ = (org.apache.avro.io.DatumWriter<Instant>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Instant>
    READER$ = (org.apache.avro.io.DatumReader<Instant>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










