/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.carrera.fhir.avro.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Meta extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9051548033077596472L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Meta\",\"namespace\":\"io.carrera.fhir.avro.models\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"]},{\"name\":\"versionId\",\"type\":[\"null\",\"string\"]},{\"name\":\"lastUpdated\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"local-timestamp-micros\"}]},{\"name\":\"source\",\"type\":[\"null\",\"string\"]},{\"name\":\"profile\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"security\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Coding\",\"fields\":[{\"name\":\"code\",\"type\":[\"null\",\"string\"]}]}}]},{\"name\":\"tag\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"Coding\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Meta> ENCODER =
      new BinaryMessageEncoder<Meta>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Meta> DECODER =
      new BinaryMessageDecoder<Meta>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Meta> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Meta> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Meta> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Meta>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Meta to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Meta from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Meta instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Meta fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence versionId;
   private java.lang.Long lastUpdated;
   private java.lang.CharSequence source;
   private java.util.List<java.lang.CharSequence> profile;
   private java.util.List<io.carrera.fhir.avro.models.Coding> security;
   private java.util.List<io.carrera.fhir.avro.models.Coding> tag;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Meta() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param versionId The new value for versionId
   * @param lastUpdated The new value for lastUpdated
   * @param source The new value for source
   * @param profile The new value for profile
   * @param security The new value for security
   * @param tag The new value for tag
   */
  public Meta(java.lang.CharSequence id, java.lang.CharSequence versionId, java.lang.Long lastUpdated, java.lang.CharSequence source, java.util.List<java.lang.CharSequence> profile, java.util.List<io.carrera.fhir.avro.models.Coding> security, java.util.List<io.carrera.fhir.avro.models.Coding> tag) {
    this.id = id;
    this.versionId = versionId;
    this.lastUpdated = lastUpdated;
    this.source = source;
    this.profile = profile;
    this.security = security;
    this.tag = tag;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return versionId;
    case 2: return lastUpdated;
    case 3: return source;
    case 4: return profile;
    case 5: return security;
    case 6: return tag;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: versionId = (java.lang.CharSequence)value$; break;
    case 2: lastUpdated = (java.lang.Long)value$; break;
    case 3: source = (java.lang.CharSequence)value$; break;
    case 4: profile = (java.util.List<java.lang.CharSequence>)value$; break;
    case 5: security = (java.util.List<io.carrera.fhir.avro.models.Coding>)value$; break;
    case 6: tag = (java.util.List<io.carrera.fhir.avro.models.Coding>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'versionId' field.
   * @return The value of the 'versionId' field.
   */
  public java.lang.CharSequence getVersionId() {
    return versionId;
  }


  /**
   * Sets the value of the 'versionId' field.
   * @param value the value to set.
   */
  public void setVersionId(java.lang.CharSequence value) {
    this.versionId = value;
  }

  /**
   * Gets the value of the 'lastUpdated' field.
   * @return The value of the 'lastUpdated' field.
   */
  public java.lang.Long getLastUpdated() {
    return lastUpdated;
  }


  /**
   * Sets the value of the 'lastUpdated' field.
   * @param value the value to set.
   */
  public void setLastUpdated(java.lang.Long value) {
    this.lastUpdated = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'profile' field.
   * @return The value of the 'profile' field.
   */
  public java.util.List<java.lang.CharSequence> getProfile() {
    return profile;
  }


  /**
   * Sets the value of the 'profile' field.
   * @param value the value to set.
   */
  public void setProfile(java.util.List<java.lang.CharSequence> value) {
    this.profile = value;
  }

  /**
   * Gets the value of the 'security' field.
   * @return The value of the 'security' field.
   */
  public java.util.List<io.carrera.fhir.avro.models.Coding> getSecurity() {
    return security;
  }


  /**
   * Sets the value of the 'security' field.
   * @param value the value to set.
   */
  public void setSecurity(java.util.List<io.carrera.fhir.avro.models.Coding> value) {
    this.security = value;
  }

  /**
   * Gets the value of the 'tag' field.
   * @return The value of the 'tag' field.
   */
  public java.util.List<io.carrera.fhir.avro.models.Coding> getTag() {
    return tag;
  }


  /**
   * Sets the value of the 'tag' field.
   * @param value the value to set.
   */
  public void setTag(java.util.List<io.carrera.fhir.avro.models.Coding> value) {
    this.tag = value;
  }

  /**
   * Creates a new Meta RecordBuilder.
   * @return A new Meta RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Meta.Builder newBuilder() {
    return new io.carrera.fhir.avro.models.Meta.Builder();
  }

  /**
   * Creates a new Meta RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Meta RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Meta.Builder newBuilder(io.carrera.fhir.avro.models.Meta.Builder other) {
    if (other == null) {
      return new io.carrera.fhir.avro.models.Meta.Builder();
    } else {
      return new io.carrera.fhir.avro.models.Meta.Builder(other);
    }
  }

  /**
   * Creates a new Meta RecordBuilder by copying an existing Meta instance.
   * @param other The existing instance to copy.
   * @return A new Meta RecordBuilder
   */
  public static io.carrera.fhir.avro.models.Meta.Builder newBuilder(io.carrera.fhir.avro.models.Meta other) {
    if (other == null) {
      return new io.carrera.fhir.avro.models.Meta.Builder();
    } else {
      return new io.carrera.fhir.avro.models.Meta.Builder(other);
    }
  }

  /**
   * RecordBuilder for Meta instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Meta>
    implements org.apache.avro.data.RecordBuilder<Meta> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence versionId;
    private java.lang.Long lastUpdated;
    private java.lang.CharSequence source;
    private java.util.List<java.lang.CharSequence> profile;
    private java.util.List<io.carrera.fhir.avro.models.Coding> security;
    private java.util.List<io.carrera.fhir.avro.models.Coding> tag;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.carrera.fhir.avro.models.Meta.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.versionId)) {
        this.versionId = data().deepCopy(fields()[1].schema(), other.versionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastUpdated)) {
        this.lastUpdated = data().deepCopy(fields()[2].schema(), other.lastUpdated);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.profile)) {
        this.profile = data().deepCopy(fields()[4].schema(), other.profile);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.security)) {
        this.security = data().deepCopy(fields()[5].schema(), other.security);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.tag)) {
        this.tag = data().deepCopy(fields()[6].schema(), other.tag);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing Meta instance
     * @param other The existing instance to copy.
     */
    private Builder(io.carrera.fhir.avro.models.Meta other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.versionId)) {
        this.versionId = data().deepCopy(fields()[1].schema(), other.versionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastUpdated)) {
        this.lastUpdated = data().deepCopy(fields()[2].schema(), other.lastUpdated);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.profile)) {
        this.profile = data().deepCopy(fields()[4].schema(), other.profile);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.security)) {
        this.security = data().deepCopy(fields()[5].schema(), other.security);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tag)) {
        this.tag = data().deepCopy(fields()[6].schema(), other.tag);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'versionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getVersionId() {
      return versionId;
    }


    /**
      * Sets the value of the 'versionId' field.
      * @param value The value of 'versionId'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setVersionId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.versionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'versionId' field has been set.
      * @return True if the 'versionId' field has been set, false otherwise.
      */
    public boolean hasVersionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'versionId' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearVersionId() {
      versionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdated' field.
      * @return The value.
      */
    public java.lang.Long getLastUpdated() {
      return lastUpdated;
    }


    /**
      * Sets the value of the 'lastUpdated' field.
      * @param value The value of 'lastUpdated'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setLastUpdated(java.lang.Long value) {
      validate(fields()[2], value);
      this.lastUpdated = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdated' field has been set.
      * @return True if the 'lastUpdated' field has been set, false otherwise.
      */
    public boolean hasLastUpdated() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastUpdated' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearLastUpdated() {
      lastUpdated = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.source = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearSource() {
      source = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'profile' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getProfile() {
      return profile;
    }


    /**
      * Sets the value of the 'profile' field.
      * @param value The value of 'profile'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setProfile(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.profile = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'profile' field has been set.
      * @return True if the 'profile' field has been set, false otherwise.
      */
    public boolean hasProfile() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'profile' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearProfile() {
      profile = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'security' field.
      * @return The value.
      */
    public java.util.List<io.carrera.fhir.avro.models.Coding> getSecurity() {
      return security;
    }


    /**
      * Sets the value of the 'security' field.
      * @param value The value of 'security'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setSecurity(java.util.List<io.carrera.fhir.avro.models.Coding> value) {
      validate(fields()[5], value);
      this.security = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'security' field has been set.
      * @return True if the 'security' field has been set, false otherwise.
      */
    public boolean hasSecurity() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'security' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearSecurity() {
      security = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'tag' field.
      * @return The value.
      */
    public java.util.List<io.carrera.fhir.avro.models.Coding> getTag() {
      return tag;
    }


    /**
      * Sets the value of the 'tag' field.
      * @param value The value of 'tag'.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder setTag(java.util.List<io.carrera.fhir.avro.models.Coding> value) {
      validate(fields()[6], value);
      this.tag = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'tag' field has been set.
      * @return True if the 'tag' field has been set, false otherwise.
      */
    public boolean hasTag() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'tag' field.
      * @return This builder.
      */
    public io.carrera.fhir.avro.models.Meta.Builder clearTag() {
      tag = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Meta build() {
      try {
        Meta record = new Meta();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.versionId = fieldSetFlags()[1] ? this.versionId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastUpdated = fieldSetFlags()[2] ? this.lastUpdated : (java.lang.Long) defaultValue(fields()[2]);
        record.source = fieldSetFlags()[3] ? this.source : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.profile = fieldSetFlags()[4] ? this.profile : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        record.security = fieldSetFlags()[5] ? this.security : (java.util.List<io.carrera.fhir.avro.models.Coding>) defaultValue(fields()[5]);
        record.tag = fieldSetFlags()[6] ? this.tag : (java.util.List<io.carrera.fhir.avro.models.Coding>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Meta>
    WRITER$ = (org.apache.avro.io.DatumWriter<Meta>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Meta>
    READER$ = (org.apache.avro.io.DatumReader<Meta>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










